name: DBConnector
version: 1.0.0
main: mc.fuckoka.dbconnector.DBConnector
description: DB接続用
author: deceitya
website: https://github.com/FuckokaMC/DBConnector
api-version: 1.21.4
load: POSTWORLD
libraries:
  - com.zaxxer:HikariCP:6.2.1
  - com.mysql:mysql-connector-j:9.2.0
