name: DBConnector
version: 1.2.0
main: mc.fuckoka.dbconnector.DBConnector
description: DB接続用
author: deceitya
website: https://github.com/FuckokaMC/DBConnector
api-version: 1.21
load: POSTWORLD
libraries:
  - com.zaxxer:HikariCP:6.2.1
  - com.mysql:mysql-connector-j:9.2.0
  - org.jetbrains.kotlin:kotlin-stdlib:2.1.10
